In [9]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [29]:
np.random.rand(3,3)

array([[0.46327177, 0.41461134, 0.57900736],
       [0.46021528, 0.47521403, 0.62940787],
       [0.68321894, 0.35917972, 0.05198192]])

In [34]:
np.random.randn(3,3)

array([[ 1.28002385, -1.22263841,  0.38540099],
       [ 0.41044219, -0.07628612,  0.27586086],
       [ 0.12657766, -1.78418258,  0.13489329]])

In [36]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [53]:
s=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(s)
print(s.ndim)
print(s.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
(3, 2, 3)


In [49]:
print(s.size)

18


In [ ]:
w=np.array([[1,2,3],[4,5,6]])
print(w.dtype)

int64


# Basic Math

In [68]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [71]:
a*b

30

In [72]:
np.sin(a)

np.float64(-0.9589242746631385)

# Matrix Multiplication


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)


array([[19, 22],
       [43, 50]])

In [74]:
A @ B

array([[19, 22],
       [43, 50]])

# Aggregation

In [75]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [76]:
arr.mean()

np.float64(2.5)

In [77]:
arr.max()

np.int64(4)

In [78]:
arr.min()

np.int64(1)

In [79]:
arr.std()

np.float64(1.118033988749895)

Indexing & Slicing

In [80]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]

array([1, 3, 5])

In [81]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

array([4, 5])

In [83]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

Reshaping & Combining Arrays

In [84]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [86]:
# Stacking
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

Broadcasting

In [87]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

Saving & Loading Arrays

In [89]:
# Save to a file
np.save('array.npy', arr)

In [93]:
# Load from a file
loaded_arr = np.load('array.npy')